#!/bin/bash
##################### GENERIC EXPORTS #####################
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.config/scripts
export PATH=$PATH:$HOME/.local/bin/
export PATH=$PATH:"/Users/Eirik/bin/FDK/Tools/osx"
export FDK_EXE="/Users/Eirik/bin/FDK/Tools/osx"
export LC_ALL=en_US.UTF-8
export EDITOR="vim"

##################### CUSTOM EXPORTS ######################
export DRIVE=$HOME/Drive
export SKOLE=$DRIVE/Skole
export PROSJEKTER=$SKOLE/Prosjekter
export CONFIG=$HOME/.config

##################### ALIAS NAVIGATION ####################
alias prosjekter="cd \$PROSJEKTER"
alias skole="cd \$SKOLE"
alias config="cd \$CONFIG"
alias f21="cd /Volumes/EirikT5/Pictures/Fuji/2021"

##################### ALIAS COMMANDS ######################
alias c='clear'
alias pwdc='pwd | pbcopy'
alias ifi='ssh eirikhsa@login.ifi.uio.no'
alias pcat='ccat ~/.bash_profile'
alias psrc='source ~/.bash_profile'
alias hb='hub browse'
alias a='atom .'
alias vim='nvim'
alias o='open .'
alias mergepdfs='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
alias mantar='curl cheat.sh/tar'

alias l='clear && exa --long --all --group-directories-first'
alias ls='exa --group-directories-first'
alias tree="clear && exa --tree --group-directories-first --git-ignore"
for i in {1..6}; do 
  aliasContent="clear && exa --tree --level=${i} --group-directories-first --git-ignore"
  alias tree${i}=${aliasContent}
done

alias t='tmux'
alias ta='tmux attach -t'
alias tn='tmux new -s'
alias tls='tmux ls'
alias tkeys='tmux list-keys | fzf'

alias sml='rlwrap sml'
alias scm='clear && rlwrap /Applications/Racket\ v7.4/bin/plt-r5rs'
alias maude='$HOME/bin/maude/maude.darwin64'

alias affirm='/Users/Eirik/Drive/Diverse/affirmations/affirmation'

alias -g FF='$(fzf)'
alias -g PF='| fzf'
alias -g CC='| pbcopy'

##################### FUNCTIONS ###########################

unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}

cdf() {
   local file
   local dir
   file=$(fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir"
 }

jc() {
  if [ "$#" -eq 0 ]; then
    javac ./*.java
  else
    javac ./*.java && java "$@"
  fi
}

mekk() {
  gaa && gcmsg "$1" && gp
}

docs() {
  livet=$1;
  case $livet in
    hoogle) open "https://hoogle.haskell.org/?hoogle=$2";;
    *) open "http://www.google.com/search?q=docs+$livet";;
  esac
}

hoogle() {
  open "https://hoogle.haskell.org/?hoogle=$1"
}

google() {
  argString=""
  for a in "$@"; do
    if [[ "${a:0:1}" != "-" ]] # Ignore flags (first character is -)
    then
      if [[ "$argString" != "" ]]
      then
        argString+="+" # Delimeter
      fi
      argString+="$a"
    fi
  done
  open "http://www.google.com/search?q=$argString";
}

function ghcid_script {
    case "$3" in

        "-l" | "--lines")
        eval "ghcid $1 --reload=$2 --test=':cmd readFile \"$2\" >>= pure . unlines . fmap (\x -> if null x then \"putStrLn mempty\" else x) . lines'"
        ;;

        "-c" | "--clear")
        eval "ghcid $1 --reload=$2 --test=':script $2'"
        ;;

        * )
        eval "ghcid $1 --reload='$2' --test=':cmd readFile \"$2\" >>= pure . unlines . init . concatMap (\x -> [\"putStrLn (\" ++ show x ++ \")\", \"putStr \\\"==>    \\\"\", x,\"putStrLn mempty\"]) . filter (not . null) . lines'"
        ;;
    esac
}

make-zip() {
  if [ "$#" -eq 0 ]; then
    echo "You need to specify files to zip"
    echo "Usage: make-zip [fileToZip]+"
    return
  fi
  make-zip-name eirikhsa "$@"
}

make-zip-name() {
  if [ "$#" -eq 0 ]; then
    echo "You need to specify a foldername and files to zip"
    echo "Usage: make-zip-name [foldername] [fileToZip]+"
    return
  elif [ "$#" -eq 1 ]; then
    echo "You need at least one file to zip"
    echo "Usage: make-zip-name [foldername] [fileToZip]+"
    return
  fi
  foldername=$1
  shift;
  mkdir "${foldername}";
  cp "$@" "${foldername}";
  tar -czf "${foldername}.tgz" "${foldername}";
  rm -rf "${foldername:?}";
}

untar() {
  if [ "$#" -eq 0 ]; then
    echo "You need to specify a file to untar"
    return
  else
    tar -xzf "$@"
  fi
}

################## NODE VERSION MANAGER ###################
export NVM_DIR="$HOME/.nvm"
 [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
 [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

######################### COLORS #########################
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

function light() {
  echo "set background=light" > ~/.vimrc_bgtype
  echo "lua require('lualine').setup{ options = { theme = \"onelight\"} }" >> ~/.vimrc_bgtype
  base16_one-light
}

function dark() {
  echo "set background=dark" > ~/.vimrc_bgtype
  echo "colorscheme gruvbox" >> ~/.vimrc_bgtype
  echo "lua require('lualine').setup{ options = { theme = \"gruvbox\"} }" >> ~/.vimrc_bgtype
  base16_gruvbox-dark-hard
}

##################### WELCOME MESSAGE #####################
clear;
echo Velkommen til terminalen Eirik!;
echo `date '+%H:%M - %d.%m.%Y'`;
echo;
