#!/bin/bash
##################### GENERIC EXPORTS #####################
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.config/scripts
export PATH=$PATH:$HOME/.local/bin/
export PATH=$PATH:"/Users/Eirik/bin/FDK/Tools/osx"
export FDK_EXE="/Users/Eirik/bin/FDK/Tools/osx"

##################### CUSTOM EXPORTS ######################
export DRIVE=$HOME/Drive
export SKOLE=$DRIVE/Skole
export PROSJEKTER=$SKOLE/Prosjekter
export CONFIG=$HOME/.config

##################### ALIAS NAVIGATION ####################
alias prosjekter="cd \$PROSJEKTER"
alias skole="cd \$SKOLE"
alias config="cd \$CONFIG"

##################### ALIAS COMMANDS ######################
alias c='clear'
alias pwdc='pwd | pbcopy'
alias ifi='ssh eirikhsa@login.ifi.uio.no'
alias pcat='ccat ~/.bash_profile'
alias psrc='source ~/.bash_profile'
alias hb='hub browse'
alias a='atom .'
alias vim='nvim'
alias o='open .'
alias mergepdfs='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
alias mantar='curl cheat.sh/tar'

alias t='tmux'
alias ta='tmux attach -t'
alias tn='tmux new -s'
alias tls='tmux ls'
alias tkeys='tmux list-keys | fzf'

alias sml='rlwrap sml'
alias scm='clear && rlwrap /Applications/Racket\ v7.4/bin/plt-r5rs'
alias maude='$HOME/bin/maude/maude.darwin64'

alias -g FF='$(fzf)'
alias -g PF='| fzf'
alias -g CC='| pbcopy'

##################### FUNCTIONS ###########################

unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}

cdf() {
   local file
   local dir
   file=$(fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir"
 }

jc() {
  if [ "$#" -eq 0 ]; then
    javac ./*.java
  else
    javac ./*.java && java "$@"
  fi
}

mekk() {
  gaa && gcmsg "$1" && gp
}

docs() {
  livet=$1;
  case $livet in
    hoogle) open "https://hoogle.haskell.org/?hoogle=$2";;
    *) open "http://www.google.com/search?q=docs+$livet";;
  esac
}

hoogle() {
  open "https://hoogle.haskell.org/?hoogle=$1"
}

hrepl() {
  if [ "$#" -eq 0 ]; then
    echo "Please supply a haskell file to start a ghcid session with"
  else
    ghcid "$1" --test=main
  fi
}

conf() {
  # inspired from guide: https://blog.htbaa.com/news/tmux-scripting

  SESSION="conf"

  # We need to manually detach the session
  # then run the command from outside of tmux
  if [ -n "$TMUX" ] ; then 
    echo "please detach before running command!"
    return
  fi

  # Attach SESSION if it already exists
  if tmux has-session -t "$SESSION" ; then
    tmux attach-session -t "$SESSION"
    return
  fi

  # Setup and attach new session otherwise
  tmux new-session -c "$HOME/.config" -n "config" -d -s "$SESSION"
  tmux split-window -c "$HOME/.config" -h

  tmux new-window -c "$HOME/.config/nvim" -t "$SESSION:2" -n "vim"
  tmux send-keys "vim init.vim" C-m

  tmux new-window -c "$HOME/.config/shell" -t "$SESSION:3" -n "shell"
  tmux send-keys "vim bash_profile" C-m

  tmux attach-session -t "$SESSION:1"

}

codewars() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: codewars [ModuleName]"
    return
  fi
  haskellModule "$1" "$PROSJEKTER/Haskell/Codewars"
}

hdiv() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: hdiv [ModuleName]"
    return
  fi
  haskellModule "$1" "$PROSJEKTER/Haskell/DivCode"
}

haskellModule() {
  # attaches a new window to the haskell tmux session (creates a new session if there isn't one)
  # The window includes three panes: 
  #   1) a vim window for the codewars module
  #   2) a ghcid window that watches the file and compiles and runs `main` on save
  #   3) a ghci window for repl-work

  # inspired from guide: https://blog.htbaa.com/news/tmux-scripting

  # tmux session name to attach window
  SESSION="hask"

  # check for module argument
  if [ "$#" -lt 2 ]; then
    echo "Usage: haskellModule [ModuleName] [Folder]"
    return
  fi

  # We need to manually detach the session
  # then run the command from outside of tmux
  if [ -n "$TMUX" ] ; then 
    echo "please detach before running command!"
    return
  fi

  HASKELL_MODULE="${1%.*}"
  HASKELL_FOLDER="$(greadlink -f "$2")"
  HASKELL_FILE="$HASKELL_FOLDER/$HASKELL_MODULE.hs"

  if test -f "$HASKELL_FILE" ; then
    echo "module already exist! Please try another module name"
    return
  fi

  touch "$HASKELL_FILE"
  echo "module $HASKELL_MODULE where"  >> "$HASKELL_FILE"
  echo ""                              >> "$HASKELL_FILE"
  echo "main :: IO ()"                 >> "$HASKELL_FILE"
  echo "main = do"                     >> "$HASKELL_FILE"
  echo "  print \"put tests here!\""   >> "$HASKELL_FILE"

  # attach haskell session and codewars window
  if tmux has-session -t "$SESSION" ; then
    tmux new-window -c "$HASKELL_FOLDER" -a -t "$SESSION" -n "$HASKELL_MODULE"
  else
    tmux new-session -c "$HASKELL_FOLDER" -n "$HASKELL_MODULE" -d -s "$SESSION"
  fi

  tmux split-window -c "$HASKELL_FOLDER" -t "$SESSION:$HASKELL_MODULE" -h
  tmux split-window -c "$HASKELL_FOLDER" -t "$SESSION:$HASKELL_MODULE" -v

  tmux send-keys -t "$SESSION:$HASKELL_MODULE.1" "vim $HASKELL_MODULE.hs" C-m
  tmux send-keys -t "$SESSION:$HASKELL_MODULE.2" "ghcid $HASKELL_MODULE.hs --test=main" C-m
  tmux send-keys -t "$SESSION:$HASKELL_MODULE.3" "ghci $HASKELL_MODULE.hs" C-m


  tmux attach-session -t "$SESSION:$HASKELL_MODULE"
}

google() {
  argString=""
  for a in "$@"; do
    if [[ "${a:0:1}" != "-" ]] # Ignore flags (first character is -)
    then
      if [[ "$argString" != "" ]]
      then
        argString+="+" # Delimeter
      fi
      argString+="$a"
    fi
  done
  open "http://www.google.com/search?q=$argString";
}

function ghcid_script {
    case "$3" in

        "-l" | "--lines")
        eval "ghcid $1 --reload=$2 --test=':cmd readFile \"$2\" >>= pure . unlines . fmap (\x -> if null x then \"putStrLn mempty\" else x) . lines'"
        ;;

        "-c" | "--clear")
        eval "ghcid $1 --reload=$2 --test=':script $2'"
        ;;

        * )
        eval "ghcid $1 --reload='$2' --test=':cmd readFile \"$2\" >>= pure . unlines . init . concatMap (\x -> [\"putStrLn (\" ++ show x ++ \")\", \"putStr \\\"==>    \\\"\", x,\"putStrLn mempty\"]) . filter (not . null) . lines'"
        ;;
    esac
}

make-zip() {
  if [ "$#" -eq 0 ]; then
    echo "You need to specify files to zip"
    echo "Usage: make-zip [fileToZip]+"
    return
  fi
  make-zip-name eirikhsa "$@"
}

make-zip-name() {
  if [ "$#" -eq 0 ]; then
    echo "You need to specify a foldername and files to zip"
    echo "Usage: make-zip-name [foldername] [fileToZip]+"
    return
  elif [ "$#" -eq 1 ]; then
    echo "You need at least one file to zip"
    echo "Usage: make-zip-name [foldername] [fileToZip]+"
    return
  fi
  foldername=$1
  shift;
  mkdir "${foldername}";
  cp "$@" "${foldername}";
  tar -czf "${foldername}.tgz" "${foldername}";
  rm -rf "${foldername:?}";
}

untar() {
  if [ "$#" -eq 0 ]; then
    echo "You need to specify a file to untar"
    return
  else
    tar -xzf "$@"
  fi
}

################## NODE VERSION MANAGER ###################
export NVM_DIR="$HOME/.nvm"
 [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
 [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

######################### COLORS #########################
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

function light() {
  echo "set background=light" > ~/.vimrc_bgtype
  base16_one-light
}

function dark() {
  echo "set background=dark" > ~/.vimrc_bgtype
  echo "colorscheme gruvbox" >> ~/.vimrc_bgtype
  base16_gruvbox-dark-hard
}

##################### WELCOME MESSAGE #####################
clear;
echo Velkommen til terminalen Eirik!;
echo `date '+%H:%M - %d.%m.%Y'`;
echo;
