#!/usr/bin/env bash

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.  Opens .sent files as sent
# presentations.  Runs scripts based on extention or shebang

file=$(greadlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
	*\.tex) pdflatex "$file" ;;
	*\.md) pandoc "$file" -o "$base".pdf ;;
	*\.py) python3 "$file" ;;
	*\.hs) runhaskell "$file" ;;
	*) printf "filetype not supported\n" ;;
esac
