#!/usr/bin/env bash

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.

function maudeAndQuit() {
  content=$(<"$1")
  "$HOME/bin/maude/maude.darwin64" -no-banner <<EOF
$content
q
EOF
}
function compileEssay() {
  export TEXINPUTS="ifimaster/:duoforside/:$(TEXINPUTS)"
  pdflatex --shell-escape "$1"
  biber thesis
  pdflatex --shell-escape "$1"
}

function compilaCompile() {
  cd /Users/Eirik/Drive/Skole/S8/INF5110/compila07/ || exit
  make
}

file=$(greadlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
  *thesis\.tex) compileEssay "$file" ;;
  /Users/Eirik/Drive/Skole/S8/INF5110/compila07/*) compilaCompile ;;
	*\.tex) pdflatex --shell-escape "$file" ;;
	*\.md) pandoc "$file" -o "$base".pdf ;;
	*\.py) python3 "$file" ;;
	*\.hs) runhaskell "$file" ;;
	*\.maude) maudeAndQuit "$file" ;;
	*) printf "filetype not supported\n" ;;
esac



