#!/usr/bin/env bash

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.

function compileEssay() {
  export TEXINPUTS="ifimaster/:duoforside/:$(TEXINPUTS)"
  pdflatex --shell-escape "$1"
  biber thesis
  pdflatex --shell-escape "$1"
}

file=$(greadlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
  *thesis\.tex) compileEssay "$file" ;;
	*\.tex) pdflatex --shell-escape "$file" ;;
	*\.md) pandoc "$file" -o "$base".pdf ;;
	*\.py) python3 "$file" ;;
	*\.hs) runhaskell "$file" ;;
	*) printf "filetype not supported\n" ;;
esac



