#!/usr/bin/env bash

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.  Opens .sent files as sent
# presentations.  Runs scripts based on extention or shebang

function watchMaude() {
  fswatch -o --event Updated "$1" | while read num ; do
    clear
    echo "running maude program ($1)"
    content=$(<"$1")
    "$HOME/bin/maude/maude.darwin64" -no-banner <<EOF
$content
q
EOF
  done
}

file=$(greadlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
  *\.maude) watchMaude $file ;;
	*\.hs) ghcid "$file" --test=main ;;
	*) printf "filetype not supported\n" ;;
esac
